name: Continuous Integration

# run on pull requests
on:
 push:

env:
  TOKEN_GITHUB: ${{secrets.TOKEN_GITHUB}}
  ORIGIN: origin

permissions:
  contents: write

jobs:
  ci-ff-only:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tell git who we are
        run: |
          set -ex
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git config --global advice.skippedCherryPicks false

      - name: Get default target branch name
        id: repo
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          set -ex
          TARGET_BRANCH=$( gh repo view --json defaultBranchRef --jq .defaultBranchRef.name )
          echo ::set-output name=target_branch::$TARGET_BRANCH

      - name: Rebased against default branch
        run: |
          set -ex
          git rebase ${ORIGIN}/${{ steps.repo.outputs.master }}
          
      - name: Do the build
        run: |
          echo This is where you run the build
        
      - name: Checkout default branch, merge only if Fast-Forward and Push back to origin
        run: |
          set -ex
          git checkout ${{ steps.repo.outputs.target_branch }}
          git pull
          git merge --ff-only ${{github.Eksamensprojekt}}
          git push ${ORIGIN} ${{ steps.repo.outputs.master }}
