name: continuous integration
run-name:  ${{ github.actor }} is trying to integrate 

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if branch can be rebased against master
        run: |
          git fetch
          if ! git rebase --onto master HEAD~1; then
            echo "Branch cannot be rebased against master. Please merge main into your branch before pushing again." >&2
            exit 1
          fi
      - name: Build with Maven
        run: mvn clean package
      - name: Push changes to master branch
        if: ${{ success() }}
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.TOKEN_GITHUB }}
