name: Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: apt-get update && apt-get install -y maven openjdk-11-jre

    - name: Deploy to Render
      uses: bounceapp/render-action@0.6.0
      with:
        renderEmail: ${{ secrets.RENDER_EMAIL }}
        renderPassword: ${{ secrets.RENDER_PASSWORD }}
        renderAccount: Mastore84
        renderService: smooth-examproject
        branch: master
