name: Deploy to Render
run-name: ${{ github.actor }} is trying to deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y maven openjdk-11-jre

    - name: Deploy to Render
      uses: bounceapp/render-action@0.6.0
      with:
         render-token: ${{ secrets.RENDER_TOKEN }}
         github-token: ${{ secrets.TOKEN_GITHUB }}
         service-id: smooth-examproject
